### ISSUE TITLE
Transcription completed successfully but I don't see any output.

### ISSUE THREAD

**Issue by zhicheng-lin** [NullMagic2/SoftWhisper#4]
OS: Windows 11
VC_redist.x64.exe: Installed
FFmpeg_Essentials.msi: Installed

![Image](https://github.com/user-attachments/assets/9f665cee-1111-45f1-ae25-2f8e07b461a1)
Transcription completed successfully but I don't see any output.

**Comment by jidechao** [comment]
me too

**Comment by dianlang** [comment]
me too tootootoo

**Comment by NullMagic2** [comment]
Hello, everyone,

After reproducing this error, I noticed it could be happening if you are pointing to the incorrect executable file.

Can you please check if the Whisper.cpp executable option is pointing to the whisper.cpp executable? 
The exact name is of the exectuable whisper-cli.exe.

For example, if your path is `D:\AI_Projects\SoftWhisper - March 2025\Whisper_win-x64`, then the executable must be `D:\AI_Projects\SoftWhisper - March 2025\Whisper_win-x64\whisper-cli.exe`.

If this fails, double check if whisper-cli is running at the console:

D:
cd 'D:\AI_Projects\SoftWhisper - March 2025\Whisper_win-x64\'
whisper-cli.exe --help

If the executable fails, it could either be corrupted or you need a different version.

**Comment by xiaofange** [comment]
In fact, after I ran pip, I didn't find the whisper-cli.exe file, and there was only one file ending with .zip in the project package?

**Comment by YuMo221130** [comment]
Same here. Point to whisper-cli.exe as below but the issue remains: complete succesfully but shows nothing output. 
I am using windows 11.

![Image](https://github.com/user-attachments/assets/1a0c93a9-43ab-487a-8d1f-2821b8dc6f1b)

**Comment by NullMagic2** [comment]
[YuMo221130](https://github.com/YuMo221130), when you run whisper-cli.exe, do you get any output?

My guess is that this build could be failing for you. What is your GPU?

**Comment by YuMo221130** [comment]
> [YuMo221130](https://github.com/YuMo221130), when you run whisper-cli.exe, do you get any output?
> 
> My guess is that this build could be failing for you. What is your GPU?

when I run whisper-cli.exe test.mp3 with command line, I got the errors below:

whisper_init_from_file_with_params_no_state: loading model from 'models/ggml-base.en.bin'
whisper_init_from_file_with_params_no_state: failed to open 'models/ggml-base.en.bin'
error: failed to initialize whisper context

the two bin files are with folder stucture models/whisper/, but even I copy the two file to models/, the error remains.
I am using NVIDIA GeForce RTX 4080 laptop GPU.

**Comment by NullMagic2** [comment]
@YuMo221130, I think I know what is going on now. 

Vulkan should work with any card. However, with your specific Nvidia card, it is failing. 
Make sure you have the Vulkan libraries installed. If you don't know how to do it or that still fails, get this release [I just built for you](https://github.com/NullMagic2/SoftWhisper/releases/download/March-2025/SoftWhisper.March.2025.NVIDIA.CUDA.support.zip). It has optimized NVIDIA / CUDA support.

Please let me know if it runs.

**Comment by YuMo221130** [comment]
@NullMagic2 Thanks for the special release. Unfortunately, it still doesn't work. Same error as before. 
I even tried to reinstall CUDA 12.8 following the steps below, but didn't help.

- Install [Microsoft Visual C++ Redistributable package](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)
- Install [Visual Studio 2022](https://visualstudio.microsoft.com/vs/preview/#download-preview). This step may not be required, but the NVIDIA CUDA Toolkit displayed a warning message during installation that Visual Studio was not detected and that it recommends installing Visual Studio before installing the CUDA Toolkit.
- Install [NVIDIA CUDA Toolkit](https://developer.nvidia.com/cuda-downloads)

**Comment by Kholtien** [comment]
I'm having the same issue as those above. I am using an AMD Radeo RX 7800 XT and with using the Whisper-cli directly, I get this output (And nothing else, no transcription file)

```
& "C:\TEMP\SoftWhisper\whisper-cli.exe" -m "C:\TEMP\SoftWhisper\models\whisper\ggml-large-v3-turbo.bin" -f "C:\TEMP\test.wav" -bs 5 -pp -l auto -oj

whisper_init_from_file_with_params_no_state: loading model from 'C:\TEMP\SoftWhisper\models\whisper\ggml-large-v3-turbo.bin'
whisper_init_with_params_no_state: use gpu    = 1
whisper_init_with_params_no_state: flash attn = 0
whisper_init_with_params_no_state: gpu_device = 0
whisper_init_with_params_no_state: dtw        = 0
ggml_vulkan: Found 1 Vulkan devices:
ggml_vulkan: 0 = AMD Radeon RX 7800 XT (AMD proprietary driver) | uma: 0 | fp16: 1 | warp size: 64 | shared memory: 32768 | matrix cores: KHR_coopmat
whisper_init_with_params_no_state: devices    = 2
whisper_init_with_params_no_state: backends   = 2
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51866
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1280
whisper_model_load: n_audio_head  = 20
whisper_model_load: n_audio_layer = 32
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1280
whisper_model_load: n_text_head   = 20
whisper_model_load: n_text_layer  = 4
whisper_model_load: n_mels        = 128
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 5 (large v3)
whisper_model_load: adding 1609 extra tokens
whisper_model_load: n_langs       = 100
whisper_model_load:  Vulkan0 total size =  1623.92 MB
whisper_model_load: model size    = 1623.92 MB
whisper_backend_init_gpu: using Vulkan0 backend
```

I also get a whole bunch of these from the debug from  your app. My VLC is fully updated:

```
[000001a9048574f0] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\stream_out\libstream_out_record_plugin.dll
[000001a9048574f0] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\stream_out\libstream_out_rtp_plugin.dll
[000001a9048574f0] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\stream_out\libstream_out_setid_plugin.dll
[000001a9048574f0] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\stream_out\libstream_out_smem_plugin.dll
[000001a9048574f0] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\stream_out\libstream_out_standard_plugin.dll
[000001a9048574f0] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\stream_out\libstream_out_stats_plugin.dll
```

**Comment by NullMagic2** [comment]
Hi, @Kholtien, 

so the error seems to come from whisper-cli directly. Have you downloaded the model before trying to run whisper-cli?
As for the libvlc errors, if they are not affecting transcription, they can be ignored for now. I'll see if I can get more insight into this issue by asking the Whisper.cpp project owner, but if everyone here could also help me investigate, it would be very helpful.

**Comment by NullMagic2** [comment]
@Kholtien @YuMo221130, we will need your patience once again.

I have patched the source code to try to make the file path handling more reliable. Please download the experimental build here: https://drive.google.com/file/d/1vx17DCXi6GqsRU7hJKygZxxL15r6FG92/view?usp=sharing

and let me know if you get different results.

**Comment by Kholtien** [comment]
Same issues, I think. Also, I think this build somehow kept your initial file location for whisper:

```
DEBUG: Widgets created.
DEBUG: Loading configuration
DEBUG: Configuration loaded.
DEBUG: Setting up callbacks
DEBUG: SoftWhisper initialization complete.
DEBUG: Entering load_model()
DEBUG: Looking for model file: models\whisper\ggml-base.bin
DEBUG: Model loaded successfully.
DEBUG: Entering mainloop
DEBUG: User requested file selection
DEBUG: File selected: C:/TEMP/Week 3 Honours Project.wav
DEBUG: Start transcription requested
DEBUG: transcribe_file() => C:/TEMP/Week 3 Honours Project.wav
DEBUG: Transcription thread started.
DEBUG: Language setting: 'auto'
DEBUG: Using Whisper executable: D:\Work\Programming\Python\SoftWhisper\Whisper_win-x64
DEBUG: Command template: D:\Work\Programming\Python\SoftWhisper\Whisper_win-x64 -m models/ggml-base.bin -f C:/TEMP/Week 3 Honours Project.wav -l auto -bs 10 -oj
DEBUG: Calling transcribe_audio()...
DEBUG: transcribe_audio() => Processing file: C:/TEMP/Week 3 Honours Project.wav
DEBUG: Running Whisper.cpp with command: D:\Work\Programming\Python\SoftWhisper\Whisper_win-x64 -m models\whisper\ggml-base.bin -f C:\Users\cmill\AppData\Local\Temp\tmp9b4exn5r.wav -bs 8 -pp -l auto -oj
DEBUG: Transcription error: [WinError 2] The system cannot find the file specified
DEBUG: User selected Whisper.cpp executable: C:/TEMP/SoftWhisper_Experimental/SoftWhisper_Experimental/Whisper_win-x64/whisper-server.exe
DEBUG: Start transcription requested
DEBUG: transcribe_file() => C:/TEMP/Week 3 Honours Project.wav
DEBUG: Transcription thread started.
DEBUG: Language setting: 'auto'
DEBUG: Using Whisper executable: C:\TEMP\SoftWhisper_Experimental\SoftWhisper_Experimental\Whisper_win-x64\whisper-server.exe
DEBUG: Command template: C:\TEMP\SoftWhisper_Experimental\SoftWhisper_Experimental\Whisper_win-x64\whisper-server.exe -m models/ggml-base.bin -f C:/TEMP/Week 3 Honours Project.wav -l auto -bs 10 -oj
DEBUG: Calling transcribe_audio()...
DEBUG: transcribe_audio() => Processing file: C:/TEMP/Week 3 Honours Project.wav
DEBUG: Running Whisper.cpp with command: C:/TEMP/SoftWhisper_Experimental/SoftWhisper_Experimental/Whisper_win-x64/whisper-server.exe -m models\whisper\ggml-base.bin -f C:\Users\cmill\AppData\Local\Temp\tmpy77149at.wav -bs 8 -pp -l auto -oj
DEBUG: Whisper.cpp process started (PID 14252).
DEBUG: Transcription completed or cancelled
DEBUG: User selected Whisper.cpp executable: C:/TEMP/SoftWhisper_Experimental/SoftWhisper_Experimental/Whisper_win-x64/whisper-server.exe
DEBUG: Start transcription requested
DEBUG: transcribe_file() => C:/TEMP/Week 3 Honours Project.wav
DEBUG: Transcription thread started.
DEBUG: Language setting: 'auto'
DEBUG: Using Whisper executable: C:\TEMP\SoftWhisper_Experimental\SoftWhisper_Experimental\Whisper_win-x64\whisper-server.exe
DEBUG: Command template: C:\TEMP\SoftWhisper_Experimental\SoftWhisper_Experimental\Whisper_win-x64\whisper-server.exe -m models/ggml-base.bin -f C:/TEMP/Week 3 Honours Project.wav -l auto -bs 10 -oj
DEBUG: Calling transcribe_audio()...
DEBUG: transcribe_audio() => Processing file: C:/TEMP/Week 3 Honours Project.wav
DEBUG: Running Whisper.cpp with command: C:/TEMP/SoftWhisper_Experimental/SoftWhisper_Experimental/Whisper_win-x64/whisper-server.exe -m models\whisper\ggml-base.bin -f C:\Users\cmill\AppData\Local\Temp\tmpksu0c8f5.wav -bs 8 -pp -l auto -oj
DEBUG: Whisper.cpp process started (PID 28436).
DEBUG: Transcription completed or cancelled
DEBUG: User selected Whisper.cpp executable: C:/TEMP/SoftWhisper_Experimental/SoftWhisper_Experimental/Whisper_win-x64/whisper-cli.exe
DEBUG: Start transcription requested
DEBUG: transcribe_file() => C:/TEMP/Week 3 Honours Project.wav
DEBUG: Transcription thread started.
DEBUG: Language setting: 'auto'
DEBUG: Using Whisper executable: C:\TEMP\SoftWhisper_Experimental\SoftWhisper_Experimental\Whisper_win-x64\whisper-cli.exe
DEBUG: Command template: C:\TEMP\SoftWhisper_Experimental\SoftWhisper_Experimental\Whisper_win-x64\whisper-cli.exe -m models/ggml-base.bin -f C:/TEMP/Week 3 Honours Project.wav -l auto -bs 10 -oj
DEBUG: Calling transcribe_audio()...
DEBUG: transcribe_audio() => Processing file: C:/TEMP/Week 3 Honours Project.wav
DEBUG: Running Whisper.cpp with command: C:/TEMP/SoftWhisper_Experimental/SoftWhisper_Experimental/Whisper_win-x64/whisper-cli.exe -m models\whisper\ggml-base.bin -f C:\Users\cmill\AppData\Local\Temp\tmp4ufvhpw7.wav -bs 8 -pp -l auto -oj
DEBUG: Whisper.cpp process started (PID 26136).
DEBUG: Transcription completed or cancelled
DEBUG: Saving configuration
DEBUG: Configuration saved.
DEBUG: Model change requested
DEBUG: Entering load_model()
DEBUG: Looking for model file: models\whisper\ggml-large-v2.bin
DEBUG: Model file not found, attempting download for ggml-large-v2.bin...
DEBUG: Downloading model from https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v2.bin
DEBUG: Download successful.
DEBUG: Model loaded successfully.
DEBUG: User requested file selection
DEBUG: File selected: C:/TEMP/Week 3 Honours Project.m4a
DEBUG: Start transcription requested
DEBUG: transcribe_file() => C:/TEMP/Week 3 Honours Project.m4a
DEBUG: Transcription thread started.
DEBUG: Language setting: 'auto'
DEBUG: Using Whisper executable: C:\TEMP\SoftWhisper_Experimental\SoftWhisper_Experimental\Whisper_win-x64\whisper-cli.exe
DEBUG: Command template: C:\TEMP\SoftWhisper_Experimental\SoftWhisper_Experimental\Whisper_win-x64\whisper-cli.exe -m models/ggml-large-v2.bin -f C:/TEMP/Week 3 Honours Project.m4a -l auto -bs 10 -oj
DEBUG: Calling transcribe_audio()...
DEBUG: transcribe_audio() => Processing file: C:/TEMP/Week 3 Honours Project.m4a
DEBUG: Running Whisper.cpp with command: C:/TEMP/SoftWhisper_Experimental/SoftWhisper_Experimental/Whisper_win-x64/whisper-cli.exe -m models\whisper\ggml-large-v2.bin -f C:\Users\cmill\AppData\Local\Temp\tmploy33oaj.wav -bs 8 -pp -l auto -oj
DEBUG: Whisper.cpp process started (PID 13068).
DEBUG: Transcription completed or cancelled
DEBUG: Saving configuration
DEBUG: Configuration saved.
DEBUG: Model change requested
DEBUG: Entering load_model()
DEBUG: Looking for model file: models\whisper\ggml-large-v3-turbo.bin
DEBUG: Model file not found, attempting download for ggml-large-v3-turbo.bin...
DEBUG: Downloading model from https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo.bin
DEBUG: Download successful.
DEBUG: Model loaded successfully.
DEBUG: User requested file selection
DEBUG: File selected: C:/TEMP/Week 3 Honours Project.m4a
DEBUG: Start transcription requested
DEBUG: transcribe_file() => C:/TEMP/Week 3 Honours Project.m4a
DEBUG: Transcription thread started.
DEBUG: Language setting: 'auto'
DEBUG: Using Whisper executable: C:\TEMP\SoftWhisper_Experimental\SoftWhisper_Experimental\Whisper_win-x64\whisper-cli.exe
DEBUG: Command template: C:\TEMP\SoftWhisper_Experimental\SoftWhisper_Experimental\Whisper_win-x64\whisper-cli.exe -m models/ggml-large-v3-turbo.bin -f C:/TEMP/Week 3 Honours Project.m4a -l auto -bs 10 -oj
DEBUG: Calling transcribe_audio()...
DEBUG: transcribe_audio() => Processing file: C:/TEMP/Week 3 Honours Project.m4a
DEBUG: Running Whisper.cpp with command: C:/TEMP/SoftWhisper_Experimental/SoftWhisper_Experimental/Whisper_win-x64/whisper-cli.exe -m models\whisper\ggml-large-v3-turbo.bin -f C:\Users\cmill\AppData\Local\Temp\tmp23kgx0q4.wav -bs 8 -pp -l auto -oj
DEBUG: Whisper.cpp process started (PID 26296).
DEBUG: Transcription completed or cancelled
DEBUG: User requested file selection
DEBUG: File selected: C:/TEMP/Week 3 Honours Project.wav
DEBUG: Start transcription requested
DEBUG: transcribe_file() => C:/TEMP/Week 3 Honours Project.wav
DEBUG: Transcription thread started.
DEBUG: Language setting: 'auto'
DEBUG: Using Whisper executable: C:\TEMP\SoftWhisper_Experimental\SoftWhisper_Experimental\Whisper_win-x64\whisper-cli.exe
DEBUG: Command template: C:\TEMP\SoftWhisper_Experimental\SoftWhisper_Experimental\Whisper_win-x64\whisper-cli.exe -m models/ggml-large-v3-turbo.bin -f C:/TEMP/Week 3 Honours Project.wav -l auto -bs 10 -oj
DEBUG: Calling transcribe_audio()...
DEBUG: transcribe_audio() => Processing file: C:/TEMP/Week 3 Honours Project.wav
DEBUG: Running Whisper.cpp with command: C:/TEMP/SoftWhisper_Experimental/SoftWhisper_Experimental/Whisper_win-x64/whisper-cli.exe -m models\whisper\ggml-large-v3-turbo.bin -f C:\Users\cmill\AppData\Local\Temp\tmpgpanjv92.wav -bs 8 -pp -l auto -oj
DEBUG: Whisper.cpp process started (PID 25376).
DEBUG: Transcription completed or cancelled
```

**Comment by Kholtien** [comment]
I even tried a couple different whisper models.

**Comment by NullMagic2** [comment]
You saw the old location because I forgot to remove the configuration file. I will fix that.
Also, my guess is that this is happening with how whisper.cpp handles file paths, but I can't quite put my finger on how.

**Comment by NullMagic2** [comment]
Hi, @Kholtien,

I'm more confident the new release will solve our problem.
It seems the real issue was that whisper-cli.exe would silently fail if you set the beam size to something bigger than 8.

I've modified our build to just ignore any value greater than what is set by whisper.cpp as the hard limit, and just use the biggest value possible instead (it was also changed to 10 instead of 8). 

The new release also fixes a few other things, such as console output working properly again into the GUI. 
Download it here: https://github.com/NullMagic2/SoftWhisper/releases/download/March-2025-v2/SoftWhisper-Release-v2-22-03-2025.zip and let me know if it works.

**Comment by Kholtien** [comment]
Now getting this when I try to select an audio file:

```
DEBUG: User requested file selection
REDIRECT: Exception in Tkinter callbackREDIRECT: Traceback (most recent call last):
REDIRECT:   File "C:\UniSoftware\Python\Python312\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
REDIRECT:   File "C:\TEMP\SoftWhisper-Release-v2-22-03-2025\SoftWhisper\SoftWhisper.py", line 714, in select_file
    initialdir=self.last_dir,
               ^^^^^^^^^^^^^
REDIRECT: AttributeError: 'SoftWhisper' object has no attribute 'last_dir'
```

Thanks so much for your effort working on this.

**Comment by Kholtien** [comment]
I just commented out line 714 and was able to get select it the audio. not sure if that line was needed... So I don't know how helpful these are: 

Logs from your app:

```
DEBUG: Widgets created.
DEBUG: Loading configuration
DEBUG: No configuration file found; using defaults.
DEBUG: Setting up callbacks
DEBUG: SoftWhisper initialization complete.
DEBUG: Entering load_model()
DEBUG: Looking for model file: models\whisper\ggml-base.bin
DEBUG: Model loaded successfully.
DEBUG: Entering mainloop
DEBUG: User requested file selection
DEBUG: File selected: C:/TEMP/SoftWhisper-Release-v2-22-03-2025/W03ProjMeeting.m4a
DEBUG: Start transcription requested
DEBUG: transcribe_file() => C:/TEMP/SoftWhisper-Release-v2-22-03-2025/W03ProjMeeting.m4a
DEBUG: Transcription thread started.
DEBUG: Language setting: 'auto'
DEBUG: Using Whisper executable: C:\TEMP\SoftWhisper-Release-v2-22-03-2025\SoftWhisper\Whisper_win-x64\whisper-cli.exe
DEBUG: Command template: C:\TEMP\SoftWhisper-Release-v2-22-03-2025\SoftWhisper\Whisper_win-x64\whisper-cli.exe -m C:\TEMP\SoftWhisper-Release-v2-22-03-2025\SoftWhisper\models\whisper\ggml-base.bin -f C:\TEMP\SoftWhisper-Release-v2-22-03-2025\W03ProjMeeting.m4a -l auto -bs 5 -oj
DEBUG: Calling transcribe_audio()...
DEBUG: transcribe_audio() => Processing file: C:\TEMP\SoftWhisper-Release-v2-22-03-2025\W03ProjMeeting.m4a
DEBUG: Running Whisper.cpp with command: C:\TEMP\SoftWhisper-Release-v2-22-03-2025\SoftWhisper\Whisper_win-x64\whisper-cli.exe -m C:\TEMP\SoftWhisper-Release-v2-22-03-2025\SoftWhisper\models\whisper\ggml-base.bin -f C:\Users\cmill\AppData\Local\Temp\tmp2a46247f.wav -bs 5 -pp -l auto -oj --prompt Always use punctuation. Do not use dashes to indicate dialog.
DEBUG: Whisper.cpp process started (PID 15172).
DEBUG: Error parsing JSON output: Expecting value: line 1 column 1 (char 0)
DEBUG: Transcription completed or cancelled
```

Logs from Whipser-cli.exe when I run that command myself (Pointing towards a wav file)

`C:\TEMP\SoftWhisper-Release-v2-22-03-2025\SoftWhisper\Whisper_win-x64\whisper-cli.exe -m C:\TEMP\SoftWhisper-Release-v2-22-03-2025\SoftWhisper\models\whisper\ggml-base.bin -f C:\temp\SoftWhisper-Release-v2-22-03-2025\W03ProjMeeting.wav -bs 5 -pp -l auto -oj`

```
whisper_init_from_file_with_params_no_state: loading model from 'C:\TEMP\SoftWhisper-Release-v2-22-03-2025\SoftWhisper\models\whisper\ggml-base.bin'
whisper_init_from_file_with_params_no_state: successfully converted path 'C:\TEMP\SoftWhisper-Release-v2-22-03-2025\SoftWhisper\models\whisper\ggml-base.bin' to wide string.
whisper_init_from_file_with_params_no_state: successfully opened file 'C:\TEMP\SoftWhisper-Release-v2-22-03-2025\SoftWhisper\models\whisper\ggml-base.bin'.
whisper_init_with_params_no_state: use gpu    = 1
whisper_init_with_params_no_state: flash attn = 0
whisper_init_with_params_no_state: gpu_device = 0
whisper_init_with_params_no_state: dtw        = 0
ggml_vulkan: Found 1 Vulkan devices:
ggml_vulkan: 0 = AMD Radeon RX 7800 XT (AMD proprietary driver) | uma: 0 | fp16: 1 | warp size: 64 | shared memory: 32768 | matrix cores: KHR_coopmat
whisper_init_with_params_no_state: devices    = 2
whisper_init_with_params_no_state: backends   = 2
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 512
whisper_model_load: n_audio_head  = 8
whisper_model_load: n_audio_layer = 6
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 512
whisper_model_load: n_text_head   = 8
whisper_model_load: n_text_layer  = 6
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 2 (base)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: n_langs       = 99
whisper_model_load:  Vulkan0 total size =   147.37 MB
whisper_model_load: model size    =  147.37 MB
whisper_init_from_file_with_params_no_state: stored file path in context successfully.
whisper_backend_init_gpu: using Vulkan0 backend
```

**Comment by NullMagic2** [comment]
Hi, @Kholtien, 

the last_dir bug was fixed.

As for the silent failure bug, it turns out it was actually a processor bug.

Apparently, we had a bigger issue: Whisper.cpp's makefile will always try to build whatever featureset you have, and my processor's feature set is not supported on older processors – specifically, it was trying to build and force the AVX 512 instruction set.

After some debugging with a few friends, I managed to build a version of whisper-cli.exe which is more compatible with older processors. Get it from here (it was updated again: https://github.com/NullMagic2/SoftWhisper/releases/download/March-2025-v2/SoftWhisper-03-23-2025.zip)

**Comment by Kholtien** [comment]
This seems to work! Thanks so much for your effort. I've run it on a 30 minute meeting I had and it was able to get it done very well, however it did just lump everything everyone said all in one big text file. Is there a way to recognize different speakers? The subtitles feature is good, and will be useful, but it still doesn't differentiate speakers. 

I can see that pyannote is in the zip under models. I've looked it up and I think it might do what I'm looking for. Is it something you will build in the future?

**Comment by NullMagic2** [comment]
Hi, @Kholtien, 

unfortunately, as I explained in the release, speaker diarization with pyannote didn't quite work as I intended. I do intend to add it later. However, since it is not working as I expected, I decided to disable it.

There's also another bug I intend to fix, which is that the text file is being saved under a different format than what was shown in the text file. But compared to this nasty processor bug, it will probably be more manageable.

**Comment by Sartek** [comment]
I helped the developer to narrow down the issue with whisper-cli.exe calling unsupported instructions on older or intel based cpus causing a silent crash.

If anyone has any further issues commenting your graphics card, cpu model and operating system would be greatly helpful in narrowing down any further issues.
